### ISSUE TITLE
请求上传接口出现异常

### ISSUE THREAD

**Issue by nenhub** [dreamncn/VPay#35]
后台上传二维码提示接口异常 php74+mysql56

**Comment by nenhub** [comment]
添加固定额度就一直处理中

**Comment by dreamncn** [comment]
自习排查问题。f12点开，console报错信息和network抓包信息一并看一下



---原始邮件---
发件人: "nenhub"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 凌晨0:31
收件人: "dreamncn/VPay"<VPay@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [dreamncn/VPay] 请求上传接口出现异常 (#35)




 
添加固定额度就一直处理中
