### ISSUE TITLE
能对接独角数卡吗

### ISSUE THREAD

**Issue by nenhub** [dreamncn/VPay#36]
怎么对接

**Comment by dreamncn** [comment]
参考开发文档https://doc.dreamn.cn/doc/Vpay%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/#/



---原始邮件---
发件人: "nenhub"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 凌晨1:49
收件人: "dreamncn/VPay"<VPay@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [dreamncn/VPay] 能对接独角数卡吗 (#36)




 
怎么对接
