### ISSUE TITLE
 关于新版本

### ISSUE THREAD

**Issue by dreamncn** [dreamncn/VPay#50]
由于我还有个项目【自动记账】https://github.com/dreamncn/Qianji_auto
所以新版本进展比较慢，耐心等吧~

**Comment by t-o-n-y-w** [comment]
最好 能顺带 吧写出 各个平台的对接插件 要不然 对于我这种没用基础的 搭建成功也 无法进行对接 其次 明年3月 就不支持个人码 收款啦 有什么新的方法吗
